src/Entity/Quiz.php
<?php

namespace App\Entity;

use App\Repository\QuizRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuizRepository::class)]
class Quiz
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;



    #[ORM\ManyToOne(inversedBy: 'quiz')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Status $status = null;


    #[ORM\OneToMany(mappedBy: 'quiz', targetEntity: Copie::class)]
    private Collection $copies;

    #[ORM\ManyToMany(targetEntity: Formation::class, inversedBy: 'quiz')]
    private Collection $formation;

    #[ORM\ManyToOne(inversedBy: 'quiz')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'quiz', targetEntity: Question::class)]
    private Collection $questions;

    #[ORM\Column(length: 255)]
    private ?float $note_max = null;

    public function __construct()
    {
        $this->copies = new ArrayCollection();
        $this->formation = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->nom;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->dateFin = $date_fin;

        return $this;
    }


    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }


    /**
     * @return Collection<int, Copie>
     */
    public function getCopies(): Collection
    {
        return $this->copies;
    }

    public function addCopy(Copie $copy): self
    {
        if (!$this->copies->contains($copy)) {
            $this->copies->add($copy);
            $copy->setQuiz($this);
        }

        return $this;
    }

    public function removeCopy(Copie $copy): self
    {
        if ($this->copies->removeElement($copy)) {
            // set the owning side to null (unless already changed)
            if ($copy->getQuiz() === $this) {
                $copy->setQuiz(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getFormation(): Collection
    {
        return $this->formation;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formation->contains($formation)) {
            $this->formation->add($formation);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        $this->formation->removeElement($formation);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setQuiz($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getQuiz() === $this) {
                $question->setQuiz(null);
            }
        }

        return $this;
    }

    public function getNoteMax(): ?float
    {
        return $this->note_max;
    }

    public function setNoteMax(float $note_max): self
    {
        $this->note_max = $note_max;

        return $this;
    }
}

src/Controller/CopieCorrectionController.php
<?php

namespace App\Controller;
use App\Entity\Copie;
use App\Entity\Quiz;
use App\Entity\Reponse;
use App\Trait\CopieCorrection;
use App\Trait\QuizSuiviTrait;
use Doctrine\ORM\EntityManagerInterface;
use http\Client\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CopieCorrectionController extends AbstractController
{
    use QuizSuiviTrait;
    #[Route('/copie/correction/{id}', name: 'app_copie_correction')]
    public function CopieCorrection(Copie $copie): Response
    {
        $currentUser = $this->getUser();

        // Nous voulons vérifier si l'utilisateur courant est en capacité d'intéragir avec le Quiz.
        $isAllowed =
            $copie->getQuiz()->getQuestions() === $currentUser ||
            $this->isGranted("ROLE_ELEVE") ||
            $this->isGranted("ROLE_PROF") ||
            $currentUser->getFormation() === $copie->getQuiz()->getFormation();

        if (!$isAllowed) {
            throw $this->createAccessDeniedException();
        }
/*       sert à afficher le résultat d'un array
         $copie->getReponses()->toArray()
        die;
         */



        return $this->render("copie_correction/CopieCorrection.html.twig", [
            "questions" => $copie->getQuiz()->getQuestions(),
//            "objects" => $objects,
            "isAllowed" => $isAllowed,
            "reponses" => $copie->getReponses(),
            "copie" => $copie,
            "quiz" => $copie->getQuiz(),
            "quizNoteMax" => $copie->getQuiz()->getNoteMax(),
        ]);
    }

    #[Route('/copie/correction/flush/{id}', name: 'app_copie_correction_flush')]
    public function CopieCorrectionFlush(Copie $copie,EntityManagerInterface $manager, \Symfony\Component\HttpFoundation\Request $request): Response
    {
        $reponses=$copie->getReponses();
        // on récupère la donnée qui a la clé "annotation-copie" dans la requête et on l'enregistre dans annotation copie
        $annotationCopie = $request->get('annotation-copie');
        $copie->setAnnotation($annotationCopie);
        // on récupère la donnée qui a la clé "annotation-note" dans la requête et on la pour dans annotation copie
        $noteCopie = $request->get('note-copie');
        $copie->setNote($noteCopie);

        // on boucle sur la requête sous forme de tableau, avec $key= "le nom du champ de formulaire" et value= "sa valeur"
        foreach ($request->request->all() as $key=>$value){
            // si la clé est différente de "annotation-copie" et "note-copie"
            if($key !== "annotation-copie" && $key !== "note-copie"){

                // on décompose la chaine de caractère de la clé avec le "-"  comme élément séparateur
                $explode=explode( "-", $key );
                //on cherche la 1ère réponse qui à l'ID = à $explode[1]
                $reponse = $reponses->findFirst(function(int $index, Reponse $reponse) use($explode): bool {
                    return $reponse->getId() == $explode[1];
                });
                // on vérifie que $explode[0] = à "annotation" avant d'envoyer  la valeur dans la table annotation
                if ("annotation" == $explode[0]){
                    $reponse->setAnnotation($value);
                }
                // on vérifie que $explode[0] = à "note" avant d'envoyer  la valeur dans la table annotation
                elseif("note"== $explode[0]){
                    $reponse->setNote($value);
                }
            }
        }
        $manager->flush();
        return $this->redirectToRoute('app_copies_du_quiz', ['id'=>$copie->getQuiz()->getId()]);
    }
}

templates/copie_correction/CopieCorrection.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CopieSuiviController!{% endblock %}

{% block body %}

    <div class="correction-copie">
        <h1>Correction de la copie</h1>
        <form action="{{path('app_copie_correction_flush', {'id': copie.id }) }}" method="post">
            {% for question in questions %}
                <div class="correction-question">
                    <h3>{{ question.question }}</h3>
                </div>
                {% for reponse in reponses  %}
                    {%  if (question.questionType.id==1) %}

                            {% if reponse.question.id == question.id %}
                                <p>{{ question.reponse1 }}
                                    <input type="checkbox" {{ reponse.choixrep1 ? "checked":"" }}/>
                                </p>
                                <p>{{ question.reponse2 }}
                                    <input type="checkbox" {{ reponse.choixrep2 ? "checked":"" }}/>
                                </p>
                                <p>{{ question.reponse3 }}
                                    <input type="checkbox" {{ reponse.choixrep3 ? "checked":"" }}/>
                                </p>
                                <p>{{ question.reponse4 }}
                                    <input type="checkbox" {{ reponse.choixrep4 ? "checked":"" }}/>
                                </p>
                                <div class="bandeau-correction">
                                    <div class="annotation-question">
                                        Annotation : <br/>
                                    <textarea name="annotation-{{ reponse.id }}">{{ reponse.annotation }}</textarea>
                                    </div>
                                    <div class="note-question">
                                        Note de la question ( / {{ question.noteMax }} )<br/>
                                        <input name="note-{{ reponse.id }}"value="{{ reponse.Note }}" type="number" min="0" max="{{ question.noteMax }}"/>
                                    </div>
                                </div>
                            {% endif %}
                            {% else %}
                                {% if reponse.question.id == question.id %}
                                    <p> <span class="intitule-reponse">Réponse :</span> {{ reponse.reponse }}
                                    </p>
                                    <div class="bandeau-correction">
                                        <div class="annotation-question">
                                            Annotation : <br/>
                                            <textarea name="annotation-{{ reponse.id }}">{{ reponse.annotation }}</textarea>
                                        </div>
                                        <div class="note-question">
                                            Note de la question ( / {{ question.noteMax }} )<br/>
                                            <input name="note-{{ reponse.id }}" value="{{ reponse.Note }}" type="number" min="0" max="{{ question.noteMax }}"/>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endif %}
                {% endfor %}
            {% endfor %}
            <div class="bandeau-correction-generale">
                <div class="annotation-generale">
                    <h2> Annotation générale</h2>
                    <textarea name="annotation-copie"> {{ copie.annotation }}</textarea>
                </div>
                <div class="note-generale">
                    <h2>Note de la copie</h2>
                    <input name="note-copie" value="{{ copie.note }}" type="number" min="0" max="{{ quizNoteMax }}"/>
                </div>
            </div>
            <div class="valider-correction">
                <button class="button" type="submit"> Valider </button>
            </div>
        </form>
    </div>
{% endblock %}